[package]
name = "moog-ladder-filter"
version = "0.1.0"
edition = "2021"

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", features = ["assert_process_allocs"] }
parking_lot = "0.12.3"

[workspace]
members = [ "xtask", ]

[lib]
crate-type = ["cdylib"]
